"""
Django settings for sleeksoft project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_URL='/upload/'
MEDIA_ROOT=os.path.join(BASE_DIR,"upload")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r58%fg4y5c!l6zf96bjvz_8q_pdcs=p3q5*)xr1u%a^x#jd!@t'
# SECRET_KEY = '1f8mthc*lg!1rl1ew%$)$wh_h30l-fmj245p0^%o1jcik8#5x1'

# RSA
PRIVATE_KEY_PEM = """-----BEGIN RSA PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALixBMVfsiJRiOCUEkF9H8HVkEVL5fqiE1kH17SF4ms+0Qhgt0US9hSLGLy2NNxlMSe42RbroLdayQGDcIVzrKyOObqt1TurHaWUjKHmiWlK1ThpZ6fL6soIxJVAhoZXVcjm+6FzMMss/jBTrWSCXxcw4SRpy1nM5Sw3CwgI0DQxAgMBAAECgYAg1pSfFVtCX9Xi/GDclQdC+xpqP8r1y8B96XeQaOevot0ezLd5SBxJ3ct5rjnq3/Ej+2lZ+m46e6FWrAyjJcSTIYGRwHrA+16zE3g/g0H7z0B6ukYynU5OVl269SzuVvb6EwzMRTvQqC9vldjgIg2s7wj5DKglqD/1s7UvVNCjywJBAP1lIW8cccuciolrp1XvIfBJkim9xq9fL2wwQLoNzpS+7oFIt3AXG8fyjpTUSxNUOofLEFe4uHh4SODIcGU0jEsCQQC6lxQIGv5EhvkCSjoZwi9V+DC6YxXAHDnrgOQZJ1ICsH2ejEBtt3NlWdkwvS0vmT8toWhG57pPuKaqFl3nNXvzAkALLIx+49g4zFxnlvG4HmV2vSfO42mBjkb/FFmmWrmDYbAOz3AXZ014Ub/r3Di7T3mNR20fESxBU7yS/QPH0rtlAkEArnkQeRfMhIV1GAgSVf22x3uBDPgT4YRDQIxQPZj/3ZXskLFymWU92RpvtVxfgS+Z3PAdkpeiJmNyLH8npUfkswJBAMASYSYoz9mLco3KxAF5uWtrzB69Zp4ffBqJFdkdZDQYKfe84AWEAdrqgK8AF+9vOR44mmolGPDIHgvPENKB9Ic=
-----END RSA PRIVATE KEY-----"""

PUBLIC_KEY_PEM = """-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC4sQTFX7IiUYjglBJBfR/B1ZBFS+X6ohNZB9e0heJrPtEIYLdFEvYUixi8tjTcZTEnuNkW66C3WskBg3CFc6ysjjm6rdU7qx2llIyh5olpStU4aWeny+rKCMSVQIaGV1XI5vuhczDLLP4wU61kgl8XMOEkactZzOUsNwsICNA0MQIDAQAB
-----END PUBLIC KEY-----"""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sleekweb',
    'django.contrib.sitemaps',
    'tailwind',
    'theme',
    'django_browser_reload',
    'corsheaders',
    
    # Thêm django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.facebook',
]

LOGIN_REDIRECT_URL = '/'
AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',  # Sử dụng tất cả các backend xác thực từ django-allauth
)
SITE_ID = 1


TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    "127.0.0.1",
]
NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"
RECAPTCHA_PUBLIC_KEY = '6LfcQBQqAAAAABePVtRoMr3SuE7-ux_nbY14LhM5'
RECAPTCHA_PRIVATE_KEY = '6LfcQBQqAAAAAHyzJZO6AqBiOj8gmUcLwE24oJYN'
AUTH_USER_MODEL = 'sleekweb.User'
# SESSION_COOKIE_AGE = 1209600
# SESSION_SAVE_EVERY_REQUEST = True
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_browser_reload.middleware.BrowserReloadMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'sleekweb.redirect_middleware.RedirectOn404Middleware',
    'sleekweb.redirect_middleware.EmailSettingsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'sleeksoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sleeksoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sleeksoft',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',  # Hoặc địa chỉ IP của máy chủ PostgreSQL
        'PORT': '5432',  # Cổng mặc định của PostgreSQL
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'sleeksoft',
#         'USER': 'sleekuser',
#         'PASSWORD': 's133ks0ft',
#         'HOST': 'localhost',
#         'PORT': '',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'Website_Account_Game',
#         'USER': 'postgres',
#         'PASSWORD': 'admin',
#         'HOST': 'localhost',  # Hoặc địa chỉ IP của máy chủ PostgreSQL
#         'PORT': '5432',  # Cổng mặc định của PostgreSQL
#     }
# }

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_USE_SSL = False
# EMAIL_PORT = 587
# EMAIL_HOST_USER = 'vuthaind@gmail.com'
# EMAIL_HOST_PASSWORD = 'yusxfqcsozyczydg'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = ''
EMAIL_USE_TLS = ''
EMAIL_USE_SSL = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''

PAGE = 10

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
