# Generated by Django 5.1.1 on 2025-02-10 14:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_USE_TLS', models.BooleanField(blank=True, default=True, null=True)),
                ('EMAIL_USE_SSL', models.BooleanField(blank=True, default=True, null=True)),
                ('EMAIL_PORT', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_HOST_USER', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_HOST_PASSWORD', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Quản lý')),
                ('Avatar', models.ImageField(blank=True, default='User_image/user_empty.png', null=True, upload_to='User_photo')),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('OTP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Otp')),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Danh mục mẹ')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Arrange', models.IntegerField(blank=True, default=0, null=True, verbose_name='Thứ tự xuất hiện')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Name'], name='sleekweb_ca_Name_dcd926_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category_product_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Danh mục con')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Category_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product_detail', to='sleekweb.category_product')),
            ],
        ),
        migrations.CreateModel(
            name='Email_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Email'], name='sleekweb_em_Email_f5dcdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã đơn hàng')),
                ('customerName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('customerEmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('customerMobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số đt')),
                ('customerAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể')),
                ('customerCity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tỉnh')),
                ('customerDistrict', models.CharField(blank=True, max_length=255, null=True, verbose_name='Huyện')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('paymentMethod', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phương thức thanh toán')),
                ('Deposit', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Tiền cọc')),
                ('Data', models.JSONField(blank=True, null=True, verbose_name='dữ liệu đơn hàng')),
                ('Status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trạng thái đơn hàng')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên sản phẩm')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Mô tả sản phẩm')),
                ('Parameter', models.TextField(blank=True, null=True, verbose_name='Thông số sản phẩm')),
                ('Choose_size', models.TextField(blank=True, null=True, verbose_name='Hướng dẫn chọn size')),
                ('Rechange', models.TextField(blank=True, null=True, verbose_name='Chính sách đổi trả')),
                ('Preserve', models.TextField(blank=True, null=True, verbose_name='hướng dẫn Bảo quản')),
                ('Discount', models.IntegerField(blank=True, null=True, verbose_name='giảm giá')),
                ('Price_Discount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá sau giảm')),
                ('Quantity_buy', models.IntegerField(blank=True, default=0, null=True, verbose_name='Số lượng đã bán')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Category_product_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product_child_detail', to='sleekweb.category_product_child')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Product_photo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Product_Photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_photo_detail', to='sleekweb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Size_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kích thước')),
                ('Quantity', models.IntegerField(blank=True, null=True, verbose_name='Số lượng trong kho')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Product_Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size_detail', to='sleekweb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên thương hiệu')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Trademark_photo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Name'], name='sleekweb_tr_Name_67e02a_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Belong_Trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product_child_detail', to='sleekweb.trademark'),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tên Website')),
                ('Email', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Email')),
                ('Phone_number', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Phone_number')),
                ('Src_Fanpage', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Đường dẫn Fanpage Facebook')),
                ('Logo', models.ImageField(blank=True, default='https://pos.nvncdn.com/609d6b-117900/store/20230522_sZKJQK5B.jpg', null=True, upload_to='Website_photo')),
                ('Banner', models.ImageField(blank=True, default='https://pos.nvncdn.com/609d6b-117900/bn/20230316_zsIiRsLe.png', null=True, upload_to='Website_photo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Name'], name='sleekweb_we_Name_d658c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='sleekweb_us_usernam_8b077a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='sleekweb_us_email_49565d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='sleekweb_us_is_staf_cf50a0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['Full_name'], name='sleekweb_us_Full_na_55d14c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_manage'], name='sleekweb_us_is_mana_d17587_idx'),
        ),
        migrations.AddIndex(
            model_name='category_product_child',
            index=models.Index(fields=['Name'], name='sleekweb_ca_Name_3a22df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['Status'], name='sleekweb_or_Status_eff7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['Belong_User'], name='sleekweb_or_Belong__2a98e8_idx'),
        ),
        migrations.AddIndex(
            model_name='photo_product',
            index=models.Index(fields=['Belong_Product_Photo'], name='sleekweb_ph_Belong__95e572_idx'),
        ),
        migrations.AddIndex(
            model_name='size_product',
            index=models.Index(fields=['Size'], name='sleekweb_si_Size_0994ec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['Name'], name='sleekweb_pr_Name_5703b6_idx'),
        ),
    ]
