# Generated by Django 5.1.1 on 2025-01-04 15:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_HOST', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_USE_TLS', models.BooleanField(blank=True, default=True, null=True)),
                ('EMAIL_USE_SSL', models.BooleanField(blank=True, default=True, null=True)),
                ('EMAIL_PORT', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_HOST_USER', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('EMAIL_HOST_PASSWORD', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='Select_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.TextField(blank=True, default='', null=True, verbose_name='Danh sách lựa chọn khu vực')),
                ('Product', models.TextField(blank=True, default='', null=True, verbose_name='Danh sách lựa chọn sản phẩm')),
                ('Demand', models.TextField(blank=True, default='', null=True, verbose_name='Danh sách lựa chọn nhu cầu')),
                ('Source', models.TextField(blank=True, default='', null=True, verbose_name='Danh sách lựa chọn nguồn')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_manage', models.BooleanField(blank=True, default=False, null=True, verbose_name='Quản lý')),
                ('Avatar', models.ImageField(blank=True, default='User_image/user_empty.png', null=True, upload_to='User_photo')),
                ('Full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('OTP', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã Otp')),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số điện thoại')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên chiến dịch')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Link_KH', models.BooleanField(blank=True, default=True, null=True, verbose_name='Link KH')),
                ('So_DT', models.BooleanField(blank=True, default=False, null=True, verbose_name='So_DT')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.ManyToManyField(blank=True, related_name='list_campaign', to=settings.AUTH_USER_MODEL)),
                ('Belong_User_Delete', models.ManyToManyField(blank=True, related_name='list_campaign_delete_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Danh mục mẹ')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Name'], name='sleekweb_ca_Name_dcd926_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category_product_child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Danh mục con')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Category_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product_detail', to='sleekweb.category_product')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên khách hàng')),
                ('Phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số đt khách hàng')),
                ('Area', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Khu vực')),
                ('Product', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Sản phẩm')),
                ('Demand', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nhu cầu')),
                ('Status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tình trạng')),
                ('Note', models.TextField(blank=True, default='', null=True, verbose_name='Ghi chú')),
                ('Status_lead', models.CharField(blank=True, default='Chưa tư vấn', max_length=255, null=True, verbose_name='Trạng thái khách hàng')),
                ('Source', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Nguồn nhập')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_campaign', to='sleekweb.campaign')),
                ('Belong_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='list_lead', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(blank=True, default='', null=True, verbose_name='Ghi chú lịch sử CSKH của NV')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_history', to='sleekweb.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Trạng thái đơn hàng')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_detail_order', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên sản phẩm')),
                ('Price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá')),
                ('Slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Category_product_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product_child_detail', to='sleekweb.category_product_child')),
            ],
        ),
        migrations.CreateModel(
            name='Photo_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='Product_photo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Product_Photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_photo_detail', to='sleekweb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số lượng dự định mua')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_detail', to='sleekweb.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số lượng mua')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sleekweb.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, default='', null=True, verbose_name='Báo cáo của NV')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_report', to='sleekweb.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Size_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kích thước')),
                ('Quantity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số lượng trong kho')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_Product_Size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_size_detail', to='sleekweb.product')),
            ],
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên thương hiệu')),
                ('Avatar', models.ImageField(blank=True, null=True, upload_to='Trademark_photo')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Name'], name='sleekweb_tr_Name_67e02a_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Belong_Trademark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product_child_detail', to='sleekweb.trademark'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='sleekweb_us_usernam_8b077a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='sleekweb_us_email_49565d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='sleekweb_us_is_staf_cf50a0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['Full_name'], name='sleekweb_us_Full_na_55d14c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_manage'], name='sleekweb_us_is_mana_d17587_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['Name'], name='sleekweb_ca_Name_aa9d76_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['Belong_User'], name='sleekweb_ca_Belong__c315c0_idx'),
        ),
        migrations.AddIndex(
            model_name='category_product_child',
            index=models.Index(fields=['Name'], name='sleekweb_ca_Name_3a22df_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['Name'], name='sleekweb_le_Name_0fa308_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['Belong_Campaign'], name='sleekweb_le_Belong__398b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['Belong_User'], name='sleekweb_le_Belong__c8a319_idx'),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['Belong_Lead'], name='sleekweb_hi_Belong__7909be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['Status'], name='sleekweb_or_Status_eff7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['Belong_User'], name='sleekweb_or_Belong__2a98e8_idx'),
        ),
        migrations.AddIndex(
            model_name='photo_product',
            index=models.Index(fields=['Belong_Product_Photo'], name='sleekweb_ph_Belong__95e572_idx'),
        ),
        migrations.AddIndex(
            model_name='product_cart',
            index=models.Index(fields=['Belong_Cart'], name='sleekweb_pr_Belong__04cd83_idx'),
        ),
        migrations.AddIndex(
            model_name='product_order',
            index=models.Index(fields=['Belong_Order'], name='sleekweb_pr_Belong__c25910_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['Belong_Lead'], name='sleekweb_re_Belong__eae8fe_idx'),
        ),
        migrations.AddIndex(
            model_name='size_product',
            index=models.Index(fields=['Size'], name='sleekweb_si_Size_0994ec_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['Name'], name='sleekweb_pr_Name_5703b6_idx'),
        ),
    ]
