# Generated by Django 5.1.1 on 2025-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Preserve',
            field=models.TextField(blank=True, null=True, verbose_name='hướng dẫn Bảo quản'),
        ),
        migrations.AddField(
            model_name='product',
            name='Rechange',
            field=models.TextField(blank=True, null=True, verbose_name='Chính sách đổi trả'),
        ),
    ]
