# Generated by Django 5.1.1 on 2025-02-10 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0002_product_preserve_product_rechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
            ],
            options={
                'indexes': [models.Index(fields=['Email'], name='sleekweb_em_Email_f5dcdd_idx')],
            },
        ),
    ]
