# Generated by Django 5.1.1 on 2025-02-10 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0003_email_information'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_order',
        ),
    ]
