# Generated by Django 5.1.1 on 2025-01-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0004_category_product_arrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mô tả sản phẩm'),
        ),
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='giảm giá'),
        ),
    ]
