# Generated by Django 5.1.1 on 2025-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0005_order_deposit_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Deposit',
            field=models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Tiền cọc'),
        ),
    ]
