# Generated by Django 5.1.1 on 2025-01-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0005_product_description_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả sản phẩm'),
        ),
    ]
