# Generated by Django 5.1.1 on 2025-02-10 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0006_alter_order_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_cart',
            name='Belong_Cart',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='Belong_Order',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Product_Cart',
        ),
        migrations.DeleteModel(
            name='Product_Order',
        ),
    ]
