# Generated by Django 5.1.1 on 2025-01-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0006_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Price_Discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá'),
        ),
    ]
