# Generated by Django 5.1.1 on 2025-01-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0007_product_price_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_Discount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Giá sau giảm'),
        ),
        migrations.AlterField(
            model_name='size_product',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượng trong kho'),
        ),
    ]
