# Generated by Django 5.1.1 on 2025-01-13 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0009_product_quantity_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='Data',
            field=models.JSONField(blank=True, null=True, verbose_name='dữ liệu đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerAddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerCity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tỉnh'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerDistrict',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Huyện'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerEmail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerMobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số đt'),
        ),
        migrations.AddField(
            model_name='order',
            name='customerName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã'),
        ),
        migrations.AlterField(
            model_name='product_order',
            name='Belong_Order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='sleekweb.order'),
        ),
        migrations.CreateModel(
            name='Address_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ và tên')),
                ('customerEmail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('customerMobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số đt')),
                ('customerAddress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể')),
                ('customerCity', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tỉnh')),
                ('customerDistrict', models.CharField(blank=True, max_length=255, null=True, verbose_name='Huyện')),
                ('ward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Xã')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('Creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('Update_time', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('Belong_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['Belong_User'], name='sleekweb_ad_Belong__b0090e_idx'), models.Index(fields=['customerName'], name='sleekweb_ad_custome_86e9dc_idx')],
            },
        ),
    ]
