# Generated by Django 5.1.1 on 2025-01-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0010_order_code_order_data_order_customeraddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Choose_size',
            field=models.TextField(blank=True, null=True, verbose_name='Hướng dẫn chọn size'),
        ),
        migrations.AddField(
            model_name='product',
            name='Parameter',
            field=models.TextField(blank=True, null=True, verbose_name='Thông số sản phẩm'),
        ),
    ]
